### ISSUE TITLE
Mismatch of cuda and pytorch version on the jupyter hub image

### ISSUE THREAD

**Issue by 27am** [SeaBee-no/snippets#2]
I was testing the hub-gpu instance. When executing this [snippet](https://github.com/SeaBeeno/snippets/blob/main/test_pytorch.ipynb) I get the following error 

`[ERROR] The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver.`

**Comment by JamesSample** [comment]
Do we have a Dockerfile somewhere for the `hub-gpu` instance, @27am ? I can't see it in the [dockerfiles](https://github.com/SeaBee-no/dockerfiles/tree/main) repository. Or are we running a "default" deployment setup by Sigma2?

**Comment by 27am** [comment]
@knl88 restored a gpu-based image for the jupyter hub through https://apps.sigma2.no/. I am saying restored because the documentation describes a "Medium" instance with GPU attached but it was not available any longer (no idea why)

You should be able to reach it via https://hub-gpu.seabee.sigma2.no/

**Comment by JamesSample** [comment]
Thanks @27am. 

Yeah, I found the instance on the apps page originally, but I didn't manage to sign in - I just see "spawn failed", which might be because someone else (your or @knl88?) is already signed in and we don't have enough GPUs to start another server.

However, if I sign in on a `standard` machine and run the `test_pytorch.ipynb`, I see a different error to the one you posted above:

`[ERROR] Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx`

This implies that the GPU-instance must have some additional configuration somewhere that's installing old NVIDIA drivers i.e. it's not running the same user environment as the `standard` and `hi-mem` machines. The other machines are using the user env built from the Dockerfile [here](https://github.com/SeaBee-no/dockerfiles/tree/main/hub-main).  

Do you or @knl88 know where the additional config. for the GPU machine is? I have a vague memory of having looked at this before, but so far I haven't managed to find anything relevant.

Thanks!

**Comment by knl88** [comment]
For the spawn problem I think that is the `cpu.limit` stopping us from signing in, we still have two GPUs. I reduced cpu on nodeodm and the gpu-hub so that we can sign in:)

The gpu config in our hub image comes from the base image `quay.io/nird-toolkit/jupyterhub-singleuser:20221107-1ada53a` that is built from an earlier version of this [Dockerfile](https://github.com/UNINETTSigma2/helm-charts-dockerfiles/blob/master/jupyterhub/singleuser/Dockerfile). I tried the default image, sigma2as/jupyterhub-singleuser:20240301-21d3e39,  from the hub helm chart but got the same error I think:/

**Comment by JamesSample** [comment]
If it's the same error in their default image it sounds like we could ask Sigma to update at their end? 

However, I guess ultimately we want to use PyTorch from the main user env, so maybe we should just update the Dockerfile [here](https://github.com/SeaBee-no/dockerfiles/tree/main/hub-main) with the correct NIVIDIA drivers and then deploy this on the gpu machine. Sound reasonable?

Do you know what kind of GPUs we have @knl88?

**Comment by knl88** [comment]
Yep, we can do that, would anyway be nice to do. Although should check once more to confirm, perhaps @27am can test it also? 

Also agree on the however, we probably want to control this a bit our self also. From nividia-smi I get

```bash
%%bash
nvidia-smi
Thu Apr 11 09:42:42 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:1A:00.0 Off |                    0 |
| N/A   37C    P0    44W / 300W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

Tesla V100-SXM2-16GB
```

**Comment by 27am** [comment]
Running

`%pip install torch==2.0.1`

at the beginning of a notebook solves the error on the mismatch of cuda and pytorch version. Perhaps we can update the [Dockerfile](https://github.com/SeaBee-no/dockerfiles/tree/main/hub-main) James mentioned?

**Comment by JamesSample** [comment]
Yeah, that makes sense. According to the [PyTorch website](https://pytorch.org/get-started/previous-versions/), v2.0.1 is the most recent version compatible with CUDA 11.7.

I guess if we switch to the other Docker image, we'll need to install all the drivers from scratch anyway. I'll have a go with CUDA 11.8 and I'll see if I can get a more recent version of PyTorch to work too.

**Comment by JamesSample** [comment]
Fixed [here](https://github.com/SeaBee-no/dockerfiles/commit/50d6163719241c92a53c4dc22d0f68f04492182f).

In the end, I just pinned torch to v2.0.1 like you suggested, @27am. It'll be interesting to see if this makes much difference to the performance of the ML!
